# 启动kong前需要先migrations一下： docker-compose run kong kong migrations bootstrap
# kong的token是Bearer {{token}}的，可以编辑kong的lua脚本来修改
version: '3.5'
services:

  kong:
    image: kong:latest
    restart: always
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_database
      KONG_CASSANDRA_CONTACT_POINTS: kong_database
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    volumes:
      - ./volumes/logs:/usr/local/kong/logs
    ports:
      - 80:8000
    links:
      - kong_database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15


  kong_database:
    image: postgres:9.5
    container_name: kong_database
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    volumes:
      - ./volumes/kong_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5


  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    ports:
      - 9000:1337
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong_database
      - DB_USER=kong


  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    ports:
      - 9001:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    ports:
      - 9002:3000


networks:
  default:
    name: tcloud_kong
    driver: bridge
